service: rey-python-otlp

provider:
  name: aws
  region: us-east-1
  runtime: python3.9
  layers:
    - arn:aws:lambda:us-east-1:425362996713:layer:Datadog-Extension:57
  environment:
    DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT: localhost:4317
    OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4317
    DD_API_KEY: ${env:DD_API_KEY}
    DD_LOG_LEVEL: DEBUG
    DD_TRACE_ENABLED: true
    DD_SERVERLESS_LOGS_ENABLED: true

package:
  patterns:
    - '!**'
    - 'handler.py'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    dockerRunCmdExtraArgs: ['--platform', 'linux/amd64']

functions:
  code:
    handler: handler.handler
    url: true
