service: rey-python-otlp

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9
  layers:
    - arn:aws:lambda:sa-east-1:425362996713:layer:Datadog-Extension-REY:7
  environment:
    DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT: localhost:4317
    OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4317

package:
  patterns:
    - '!**'
    - 'handler.py'

plugins:
  - serverless-plugin-datadog
  - serverless-python-requirements

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
    logLevel: DEBUG
    addExtension: false
  pythonRequirements:
    dockerizePip: true
    dockerRunCmdExtraArgs: ['--platform', 'linux/amd64']

functions:
  code:
    handler: handler.handler
    url: true
