service: rey-python-otlp

provider:
  name: aws
  runtime: python3.9
  region: sa-east-1
  layers:
    - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:41
  environment:
    DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT: localhost:4318
    OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4318
    DD_API_KEY: ${env:DD_API_KEY}
    DD_LOG_LEVEL: DEBUG
    DD_TRACE_ENABLED: true
    DD_SERVERLESS_LOGS_ENABLED: true

package:
  patterns:
    - '!**'
    - 'handler.py'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    dockerRunCmdExtraArgs: ['--platform', 'linux/amd64']

functions:
  code:
    handler: handler.handler
    url: true
