service: rey-python-mem-usage

provider:
  name: aws
  region: sa-east-1
  architecture: arm64
  environment:
    DD_LOG_LEVEL: debug
    DD_TRACE_DEBUG: true

layers:
  numpy:
    package:
      artifact:
        numpy-deps.zip

package:
  patterns:
    - '!**'
    - 'handler.*'
    - 'bigimport.*'

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
    addLayers: false

functions:
  python:
    runtime: python3.12
    handler: handler.handler
    url: true
    layers:
      - arn:aws:lambda:sa-east-1:425362996713:layer:Python312-REY:16
      - !Ref NumpyLambdaLayer

  node:
    runtime: nodejs18.x
    handler: handler.handler
    url: true
    layers:
      - arn:aws:lambda:sa-east-1:425362996713:layer:datadog-lambda-js-REY:3
