service: rey-python-mem-usage

provider:
  name: aws
  region: sa-east-1
  runtime: python3.12
  architecture: arm64
  layers:
    - arn:aws:lambda:sa-east-1:425362996713:layer:Python312-REY:15
    - !Ref NumpyLambdaLayer

layers:
  numpy:
    package:
      artifact:
        numpy-deps.zip

package:
  patterns:
    - '!**'
    - 'handler.py'
    - 'bigimport.py'

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
    addLayers: false

functions:
  fn:
    handler: handler.handler
    url: true
