service: rey-python-fastapi

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9

package:
  patterns:
    - '!**'
    - 'main.py'

plugins:
  - serverless-plugin-datadog
  - serverless-python-requirements

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}

functions:
  fastapi:
    handler: main.handler
    url: true
