service: rey-java-lambda

provider:
  name: aws
  region: sa-east-1
  runtime: java11
  environment:
    DD_API_KEY: ${env:DD_API_KEY}

package:
  artifact: build/distributions/lambda.zip

plugins:
  - serverless-plugin-datadog

functions:
  simple:
    handler: example.Handler
    url: true
    environment:
      DD_LOG_LEVEL: debug
