service: rey-rust-lambda

provider:
  name: aws
  region: sa-east-1
  runtime: provided.al2023

package:
  artifact: target/lambda/rey-rust-lambda/bootstrap.zip

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}

functions:
  simple:
    handler: bootstrap
    url: true
