receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  batch:

exporters:
  file:
    path: /tmp/export.json

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
