service: rey-python-otlp

provider:
  name: aws
  runtime: python3.9
  region: sa-east-1
  layers:
    - arn:aws:lambda:sa-east-1:901920570463:layer:aws-otel-python-amd64-ver-1-21-0:1
  environment:
    AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
  tracing:
    lambda: true

package:
  patterns:
    - '!**'
    - 'handler.py'

functions:
  code:
    handler: handler.handler
    url: true
