service: rey-app-otlp

plugins:
  - serverless-python-requirements

provider:
  name: aws
  region: sa-east-1
  environment:
    DD_API_KEY: ${env:DD_API_KEY}
    DD_SITE: ${env:DD_SITE}
    DD_LOG_LEVEL: DEBUG
    DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT: localhost:4318
    DD_SERVERLESS_LOGS_ENABLED: true
    DD_TRACE_ENABLED: true
  layers:
    - ${self:custom.ddLayer}

custom:
  ddLayer: arn:aws:lambda:sa-east-1:425362996713:layer:Datadog-Extension-REY:77
  pythonRequirements:
    dockerRunCmdExtraArgs: ['--platform', 'linux/amd64']
    dockerizePip: true
    fileName: python/requirements.txt
    layer:
      compatibleRuntimes:
        - python3.9

functions:

  golang:
    handler: handler
    runtime: go1.x
    url: true
    package:
      artifact: .artifacts/golang.zip
      individually: true
    environment:
      DD_SERVICE: rey-app-otlp-dev-golang

  node:
    handler: handler.handler
    runtime: nodejs18.x
    url: true
    package:
      artifact: .artifacts/node.zip
      individually: true
    environment:
      DD_SERVICE: rey-app-otlp-dev-node
      NODE_OPTIONS: --require instrument

  python:
    handler: handler.handler
    runtime: python3.9
    url: true
    layers:
      - ${self:custom.ddLayer}
      - { Ref: PythonRequirementsLambdaLayer }
    package:
      artifact: .artifacts/python.zip
      individually: true
    environment:
      DD_SERVICE: rey-app-otlp-dev-python
