service: rey-go-sqs

provider:
  name: aws
  region: sa-east-1
  runtime: provided.al2
  environment:
    DD_SERVICE: ${self:service}
    DD_UNIVERSAL_INSTRUMENTATION: true
    SQS_QUEUE_URL: ${construct:sqs.queueUrl}
    DD_CAPTURE_LAMBDA_PAYLOAD: true

plugins:
  - serverless-plugin-datadog
  - serverless-lift

package:
  patterns:
    - '!**'
    - '**/bootstrap'

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}

constructs:
  sqs:
    type: queue
    worker:
      handler: bootstrap
      runtime: provided.al2
      name: ${self:service}-${sls:stage}-consumer

functions:
  producer:
    handler: bootstrap
    url: true
