service: rey-python-flask

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9
  architecture: arm64

package:
  patterns:
    - '!**'
    - 'app.py'

plugins:
  - serverless-plugin-datadog
  - serverless-wsgi
  - serverless-python-requirements

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
  wsgi:
    app: app.app

functions:
  func:
    handler: wsgi_handler.handler
    url: true
