service: rey-java-stream-handler

provider:
  name: aws
  region: sa-east-1
  runtime: java11
  architecture: arm64

package:
  artifact: build/distributions/lambda.zip

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
    captureLambdaPayload: true
    logLevel: debug

functions:
  stream:
    handler: example.Handler
    url: true
