dist:
  name: otelcol-custom
  output_path: .layers/extensions/bin

exporters:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter v0.100.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.100.0
