receivers:
  otlp:
    protocols:
      http:
        endpoint: "localhost:4318"

exporters:
  datadog:
    api:
      site: datadoghq.com
      key: ${env:DD_API_KEY}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [datadog]
