version: '2'

services:
  app:
    image: python-base
    build: .
    depends_on:
      - mysql_one
      - mysql_two
    volumes:
      - .:/data
      - $PYAGENT_DIR:/agent
    entrypoint: /data/entrypoint.sh
    command: python /data/app.py
  mysql_one:
    image: mysql
  mysql_two:
    image: mysql
