service: python-telemetry-rey

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9
  tracing:
    lambda: true
    apiGateway: true
  environment:
    # Use this to switch between logs/telemetry apis when using REY ext 34
    REY_USE_TELEMETRY_API: true
  layers:
    # prints payloads for all but "extension" type events
    # must manually remove one of the extensions before running
    - arn:aws:lambda:sa-east-1:601427279990:layer:Datadog-Extension-REY:34

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
    logLevel: DEBUG

functions:
  simple:
    handler: handler.handler
  long-init:
    handler: handler.handler
    environment:
      REY_INIT_SLEEP_TIME: 5.0
  fail-init:
    handler: handler.handler
    environment:
      REY_INIT_FAIL: true
  timeout-init:
    handler: handler.handler
    environment:
      REY_INIT_SLEEP_TIME: 1000000.0
