service: python-telemetry-rey

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9
  timeout: 20  # default is 6
  tracing:
    lambda: true
    apiGateway: true
  environment:
    # Use this to switch between logs/telemetry apis when using REY ext 34
    REY_USE_TELEMETRY_API: true
    REY_FUNCTION_SLEEP_TIME: 3.0
  layers:
    # must manually remove one of the extensions before running
    - arn:aws:lambda:sa-east-1:601427279990:layer:Datadog-Extension-REY:46

package:
  include:
    - handler.py

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
    logLevel: DEBUG

functions:
  simple:
    handler: handler.handler
    events:
      - http: GET /simple
  long-init:
    handler: handler.handler
    environment:
      REY_INIT_SLEEP_TIME: 5.0
    events:
      - http: GET /long-init
  timeout-init:
    handler: handler.handler
    environment:
      REY_INIT_SLEEP_TIME: 1000000.0
    events:
      - http: GET /timeout-init
  fail-once:
    handler: handler.handler
    environment:
      REY_INIT_SLEEP_TIME: 2.0
      REY_INIT_FAIL_FIRST_TIME: true
      REY_INIT_FAIL_SECOND_TIME: false
    events:
      - http: GET /fail-once
  fail-both:
    handler: handler.handler
    environment:
      REY_INIT_SLEEP_TIME: 1.0
      REY_INIT_FAIL_FIRST_TIME: true
      REY_INIT_FAIL_SECOND_TIME: true
    events:
      - http: GET /fail-both
  # TODO: OOM
