service: rey-python-vercel

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9
  environment:
    DD_LOG_LEVEL: trace

package:
  patterns:
    - '!**'
    - 'handler.py'
    - 'trace.json'

functions:
  with-orig-extension:
    handler: handler.handler
    url: true
    layers:
      - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:35
  with-new-extension:
    handler: handler.handler
    url: true
    layers:
      - arn:aws:lambda:sa-east-1:601427279990:layer:Datadog-Extension-REY:85
  with-two-extensions:
    handler: handler.handler
    url: true
    layers:
      - arn:aws:lambda:sa-east-1:601427279990:layer:Datadog-Extension-REY:85
      - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:35
  with-two-exentions-manual-instrumentation:
    handler: handler.handler
    url: true
    environment:
      REY_MANUALLY_INSTRUMENT: true
    layers:
      - arn:aws:lambda:sa-east-1:601427279990:layer:Datadog-Extension-REY:85
      - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:35
  with-two-exentions-and-layer:
    handler: handler.handler
    url: true
    layers:
      - arn:aws:lambda:sa-east-1:601427279990:layer:Datadog-Extension-REY:85
      - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:35
      - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Python39:64
