service: rey-python-vercel

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9
  environment:
    DD_LOG_LEVEL: debug

package:
  patterns:
    - '!**'
    - 'handler.py'

functions:
#  with-new-extension:
#    handler: handler.handler
#    url: true
#    environment:
#      REY_SERVICE: with-new-extension
#    layers:
#      - arn:aws:lambda:ap-south-1:425362996713:layer:Datadog-Extension-OTEL:3
#  with-two-extensions:
#    handler: handler.handler
#    url: true
#    environment:
#      REY_SERVICE: with-two-exentions
#    layers:
#      - arn:aws:lambda:sa-east-1:601427279990:layer:Datadog-Extension-REY:100
#      - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:35
  with-two-exentions-instrumented:
    handler: datadog_lambda.handler.handler
    url: true
    environment:
      DD_API_KEY: ${env:DD_API_KEY}
      DD_LAMBDA_HANDLER: handler.handler
      DD_SERVICE: otel-forwarder
      DD_SITE: ${env:DD_SITE}
      REY_SERVICE: with-two-exentions-instrumented
    layers:
      - arn:aws:lambda:sa-east-1:425362996713:layer:Datadog-Extension-OTEL:31
      - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:35
      - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Python39:64
#  with-two-exentions-manual:
#    handler: handler.handler
#    url: true
#    environment:
#      DD_API_KEY: ${env:DD_API_KEY}
#      DD_SITE: ${env:DD_SITE}
#      DD_SERVICE: otel-forwarder
#      REY_MANUALLY_INSTRUMENT: true
#      REY_SERVICE: with-two-extensions-manual
#    layers:
#      - arn:aws:lambda:sa-east-1:601427279990:layer:Datadog-Extension-REY:101
#      - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:35
#      - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Python39:64
