service: rey-python-vercel

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9
  environment:
    DD_LOG_LEVEL: debug
  stackTags:
    DD_PRESERVE_STACK: true

package:
  patterns:
    - '!**'
    - 'handler.py'
    - 'trace.json'

functions:
  otel-forwarder:
    handler: datadog_lambda.handler.handler
    url: true
    environment:
      DD_API_KEY: ${env:DD_API_KEY}
      DD_LAMBDA_HANDLER: handler.handler
      DD_SERVICE: otel-forwarder
      DD_SITE: ${env:DD_SITE}
    layers:
      - arn:aws:lambda:sa-east-1:425362996713:layer:Datadog-Extension-REY:18
      - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:36
      - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Python39:66
    events:
      - schedule: rate(1 minute)
