service: rey-rust-lambda

provider:
  name: aws
  region: sa-east-1
  runtime: provided.al2023
  layers:
    - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:57
  environment:
    DD_API_KEY: ${env:DD_API_KEY}
    DD_ENV: dev
    DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT: localhost:4317
    DD_SERVICE: rey-rust-lambda

    SAMPLING_RATIO: 1.0
    SERVICE_NAME: rey-rust-lambda
    URL: http://localhost:4317

package:
  artifact: target/lambda/missing-span-sample/bootstrap.zip

functions:
  simple:
    handler: bootstrap
    url: true
