service: rey-python-otlp

provider:
  name: aws
  runtime: python3.9
  region: sa-east-1
  layers:
    - arn:aws:lambda:sa-east-1:184161586896:layer:opentelemetry-python-0_1_0:1
    - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:56
  environment:
    AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument

    OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4318
    OTEL_TRACES_EXPORTER: otlp

    DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT: localhost:4318
    DD_API_KEY: ${env:DD_API_KEY}
    DD_ENV: dev
    DD_LOG_LEVEL: DEBUG
    DD_SERVERLESS_LOGS_ENABLED: true
    DD_SERVICE: rey-python-otlp
    DD_TRACE_ENABLED: true

package:
  patterns:
    - '!**'
    - 'handler.py'

functions:
  code:
    handler: handler.handler
    url: true
