service: rey-python-lambda

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9
  layers:
    - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:44

package:
  patterns:
    - '!**'
    - 'handler.py'

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    logLevel: DEBUG
    addExtension: false
    apiKey: ${env:DD_API_KEY}

functions:
  simple:
    handler: handler.handler
    url: true
