service: rey-python-lambda

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9
  environment:
    DD_API_KEY: ${env:DD_API_KEY}
  layers:
    #- arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:29
    - arn:aws:lambda:sa-east-1:601427279990:layer:Datadog-Extension-REY:55

package:
  patterns:
    - '!**'
    - 'handler.py'

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    logLevel: DEBUG
    addExtension: false

functions:
  simple:
    handler: handler.handler
    events:
      - http: GET /simple
