service: rey-python-lambda

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9

package:
  patterns:
    - '!**'
    - 'handler.py'

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}

functions:
  simple:
    handler: handler.handler
    url: true
