service: python-function-rey

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9

package:
  patterns:
    - '*.py'

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
    logLevel: DEBUG

functions:
  simple:
    handler: handler.handler
    events:
      - http: GET /simple
