service: python-function-rey

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9
  environment:
    DD_TRACE_DEBUG: true
  layers:
    - arn:aws:lambda:sa-east-1:601427279990:layer:Datadog-Extension-REY:20

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
    logLevel: DEBUG

functions:
  simple:
    handler: handler.handler
