service: rey-go-lambda

provider:
  name: aws
  region: sa-east-1
  runtime: provided.al2
  environment:
    DD_API_KEY: ${env:DD_API_KEY}

plugins:
  - serverless-plugin-datadog

package:
  patterns:
    - '!**'
    - './bootstrap'

functions:
  me:
    handler: bootstrap
    url: true
