service: rey-go-lambda

provider:
  name: aws
  region: sa-east-1
  runtime: go1.x
  environment:
    DD_API_KEY: ${env:DD_API_KEY}

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    logLevel: DEBUG

package:
  patterns:
    - '!**'
    - './bin/**'

functions:
  simple:
    handler: bin/handler
    url: true
