service: rey-go-lambda

provider:
  name: aws
  region: sa-east-1
  runtime: go1.x
  environment:
    DD_API_KEY: ${env:DD_API_KEY}
    DD_RUNTIME_METRICS_ENABLED: true
  layers:
    #- arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:29
    - arn:aws:lambda:sa-east-1:601427279990:layer:Datadog-Extension-REY:62

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    logLevel: DEBUG
    addExtension: false

package:
  patterns:
    - '!**'
    - './bin/**'

functions:
  simple:
    handler: bin/handler
    events:
      - http: GET /simple
