service: rey-node-lambda

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs18.x

package:
  patterns:
    - '!**'
    - 'handler.js'

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    logLevel: DEBUG
    apiKey: ${env:DD_API_KEY}
    addLayers: false

functions:
  simple:
    handler: handler.handler
    url: true
