CONTENT_TYPE = "content-type"
FORM_MIMETYPE = "application/x-www-form-urlencoded"
HTML_MIMETYPE = "text/html"
JS_MIMETYPE = "application/javascript"
JSON_MIMETYPE = "application/json"
PNG_MIMETYPE = "image/png"
