service: rey-python-lambda

provider:
  name: aws
  region: sa-east-1
  runtime: python3.9
  environment:
    DD_TRACE_OTEL_ENABLED: true
    DD_SERVICE: rey-ddtrace-otel
    DD_ENV: rey

package:
  patterns:
    - '!**'
    - 'handler.py'

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}

functions:
  simple:
    handler: handler.handler
    url: true
