service: sqs-trace-propagation

provider:
  name: aws
  region: sa-east-1
  architecture: arm64
  environment:
    SQS_QUEUE_URLS: !Join [ ",", "${self:custom.queueUrls}"]

plugins:
  - serverless-plugin-datadog
  - serverless-lift

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
  queueUrls:
    - ${construct:python-sqs.queueUrl}

constructs:
  python-sqs:
    type: queue
    worker:
      handler: python/handlers.consumer
      runtime: python3.9
      name: ${self:service}-${sls:stage}-python-consumer

functions:
  python-producer:
    handler: python/handlers.producer
    runtime: python3.9
    url: true
