service: sqs-trace-propagation

provider:
  name: aws
  region: sa-east-1
  architecture: arm64
  timeout: 90
  environment:
    SQS_QUEUE_URLS: !Join [",", "${self:custom.queueUrls}"]

plugins:
  - serverless-plugin-datadog
  - serverless-lift

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
  queueUrls:
    - ${construct:python-sqs.queueUrl}
    - ${construct:java-sqs.queueUrl}
  producerUrls:
    - !GetAtt PythonDashproducerLambdaFunctionUrl.FunctionUrl
    - !GetAtt JavaDashproducerLambdaFunctionUrl.FunctionUrl

constructs:
  python-sqs:
    type: queue
    worker:
      handler: python/handlers.consumer
      runtime: python3.9
      name: ${self:service}-${sls:stage}-python-consumer
  java-sqs:
    type: queue
    worker:
      handler: example.Consumer
      runtime: java11
      name: ${self:service}-${sls:stage}-java-consumer
      package:
        artifact: java/build/distributions/java.zip

functions:
  python-producer:
    handler: python/handlers.producer
    runtime: python3.9
    url: true
  java-producer:
    handler: example.Producer
    runtime: java11
    url: true
    package:
      artifact: java/build/distributions/java.zip
  orchestrator:
    handler: orchestrator/handlers.orchestrate
    runtime: python3.9
    url: true
    environment:
      PRODUCER_URLS: !Join [",", "${self:custom.producerUrls}"]
