service: sqs-trace-propagation

provider:
  name: aws
  region: sa-east-1
  timeout: 30
  environment:
    SQS_QUEUE_URLS: !Join [",", "${self:custom.queueUrls}"]
  layers:
    - arn:aws:lambda:sa-east-1:425362996713:layer:Datadog-Extension-REY:81

plugins:
  - serverless-plugin-datadog
  - serverless-lift

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
    addExtension: false
  queueUrls:
    - ${construct:python-sqs.queueUrl}
    - ${construct:java-sqs.queueUrl}
    - ${construct:go-sqs.queueUrl}
  producerUrls:
    - !GetAtt PythonDashproducerLambdaFunctionUrl.FunctionUrl
    - !GetAtt JavaDashproducerLambdaFunctionUrl.FunctionUrl
    - !GetAtt GoDashproducerLambdaFunctionUrl.FunctionUrl

constructs:
  python-sqs:
    type: queue
    worker:
      handler: python/handlers.consumer
      runtime: python3.9
      name: ${self:service}-${sls:stage}-python-consumer
  java-sqs:
    type: queue
    worker:
      handler: example.Consumer
      runtime: java11
      name: ${self:service}-${sls:stage}-java-consumer
      package:
        artifact: java/build/distributions/java.zip
  go-sqs:
    type: queue
    worker:
      handler: golang/bin/consumer
      runtime: go1.x
      name: ${self:service}-${sls:stage}-go-consumer
      environment:
        DD_UNIVERSAL_INSTRUMENTATION: true

functions:
  python-producer:
    handler: python/handlers.producer
    runtime: python3.9
    url: true
  java-producer:
    handler: example.Producer
    runtime: java11
    url: true
    package:
      artifact: java/build/distributions/java.zip
  go-producer:
    handler: golang/bin/producer
    runtime: go1.x
    url: true
    environment:
      DD_UNIVERSAL_INSTRUMENTATION: true
  orchestrator:
    handler: orchestrator/handlers.orchestrate
    runtime: python3.9
    url: true
    environment:
      PRODUCER_URLS: !Join [",", "${self:custom.producerUrls}"]
