service: rey-dotnet-lambda

frameworkVersion: ^3.21.0

provider:
  name: aws
  region: sa-east-1
  runtime: dotnet6
  tracing:
    lambda: false
  environment:
    AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
    DD_API_KEY: ${env:DD_API_KEY}
    DD_CAPTURE_LAMBDA_PAYLOAD: true
    DD_DOTNET_TRACER_HOME: /opt/datadog
    DD_INTEGRATIONS: /opt/datadog/integrations.json
    DD_LOGS_ENABLED: true
    DD_LOGS_INJECTION: true
    DD_LOG_LEVEL: debug
    DD_MERGE_XRAY_TRACES: false
    DD_SERVERLESS_LOGS_ENABLED: true
    DD_SERVICE: dotnet-function-rey
    DD_SITE: datadoghq.com
    DD_TRACE_DEBUG: true
    DD_TRACE_ENABLED: true
    DD_TRACE_MANAGED_SERVICES: true
  layers:
    ##### TRACER LAYERS #####

    # public version
    - arn:aws:lambda:sa-east-1:464622532012:layer:dd-trace-dotnet:6

    # build of https://github.com/DataDog/dd-trace-dotnet/pull/3275
    #- arn:aws:lambda:sa-east-1:601427279990:layer:dotnet-tracer-rey:18

    ##### EXTENSION LAYERS #####

    # public version
    #- arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:29

    # logs when StartInvocation route is hit
    - arn:aws:lambda:sa-east-1:601427279990:layer:Datadog-Extension-REY:57

package:
  artifact: .package/handler.zip

functions:
  # async handlers, return string
  dict-param:
    handler: MyFunction::MyFunction.Function::HandlerDictParam
  string-param:
    handler: MyFunction::MyFunction.Function::HandlerStringParam
  apigateway-param:
    handler: MyFunction::MyFunction.Function::HandlerAPIGatewayParam
  no-param:
    handler: MyFunction::MyFunction.Function::HandlerNoParam
  custom-struct-param:
    handler: MyFunction::MyFunction.Function::HandlerCustomStructParam
    environment:
      REY_PARAM_TYPE: MyInputType

  # non-async handlers, return string
  dict-param-sync:
    handler: MyFunction::MyFunction.Function::HandlerDictParamSync
  string-param-sync:
    handler: MyFunction::MyFunction.Function::HandlerStringParamSync
  apigateway-param-sync:
    handler: MyFunction::MyFunction.Function::HandlerAPIGatewayParamSync
  no-param-sync:
    handler: MyFunction::MyFunction.Function::HandlerNoParamSync
  custom-struct-param-sync:
    handler: MyFunction::MyFunction.Function::HandlerCustomStructParamSync
    environment:
      REY_PARAM_TYPE: MyInputType

  # async handlers, return void
  dict-param-void:
    handler: MyFunction::MyFunction.Function::HandlerDictParamVoid
  string-param-void:
    handler: MyFunction::MyFunction.Function::HandlerStringParamVoid
  apigateway-param-void:
    handler: MyFunction::MyFunction.Function::HandlerAPIGatewayParamVoid
  no-param-void:
    handler: MyFunction::MyFunction.Function::HandlerNoParamVoid
  custom-struct-param-void:
    handler: MyFunction::MyFunction.Function::HandlerCustomStructParamVoid
    environment:
      REY_PARAM_TYPE: MyInputType

  # non-async handlers, return void
  dict-param-sync-void:
    handler: MyFunction::MyFunction.Function::HandlerDictParamSyncVoid
  string-param-sync-void:
    handler: MyFunction::MyFunction.Function::HandlerStringParamSyncVoid
  apigateway-param-sync-void:
    handler: MyFunction::MyFunction.Function::HandlerAPIGatewayParamSyncVoid
  no-param-sync-void:
    handler: MyFunction::MyFunction.Function::HandlerNoParamSyncVoid
  custom-struct-param-sync-void:
    handler: MyFunction::MyFunction.Function::HandlerCustomStructParamSyncVoid
    environment:
      REY_PARAM_TYPE: MyInputType

  # inherited handlers
  inherited-in-child-class:
    handler: MyFunction::MyFunction.Function::InheritedHandlerInChildClass
  inherited-not-in-child-class:
    handler: MyFunction::MyFunction.Function::InheritedHandlerNotInChildClass
