service: rey-java-custom-metric

provider:
  name: aws
  region: sa-east-1
  runtime: java11
  memorySize: 1024
  environment:
    DD_API_KEY: ${env:DD_API_KEY}

layers:
  tracer:
    package:
      artifact: tracer.zip

package:
  artifact: build/distributions/custom-metric.zip

plugins:
  - serverless-plugin-datadog

functions:
  simple:
    handler: example.Handler
    url: true
    layers:
      - !Ref TracerLambdaLayer
