service: rey-node-sns

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs18.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource:
        - arn:aws:sns:sa-east-1:425362996713:rey-sns

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
    captureLambdaPayload: true
    coldStartTracingEnabled: false

functions:
  producer:
    handler: handler.producer
    environment:
      TOPIC_ARN: arn:aws:sns:sa-east-1:425362996713:rey-sns
    url: true
  consumer:
    handler: handler.consumer
    events:
      #- sns: arn:aws:sns:sa-east-1:425362996713:rey-sns
      - sns: rey-sns
