service: rey-app-pgo

provider:
  name: aws
  region: sa-east-1
  runtime: provided.al2
  environment:
    DD_SERVICE: rey-app-pgo
    DD_ENV: dev

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}
    captureLambdaPayload: true
    addExtension: false

package:
  patterns:
    - '!**'
    - './bootstrap'

functions:
  optimized:
    handler: bootstrap
    url: true
    layers:
      - arn:aws:lambda:sa-east-1:425362996713:layer:Datadog-Extension-REY:133
  normal:
    handler: bootstrap
    url: true
    layers:
      - arn:aws:lambda:sa-east-1:425362996713:layer:Datadog-Extension-REY:134
