service: rey-python-profiling

provider:
  name: aws
  region: sa-east-1
  runtime: python3.12
  timeout: 120
  environment:
    DD_PROFILING_ENABLED: true

package:
  patterns:
    - '!**'
    - 'handler.py'

plugins:
  - serverless-plugin-datadog

custom:
  datadog:
    apiKey: ${env:DD_API_KEY}

functions:
  fn:
    handler: handler.handler
    url: true
