version: '2'
services:
  packnsend:
    build: .
    image: python-base
    depends_on:
      - mongo
    volumes:
      - .:/data
    environment:
      NEW_RELIC_CONFIG_FILE: /data/newrelic.ini
    command: python /data/app.py
  mongo:
    image: mongodb
