service: rey-node-otlp

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs18.x
  layers:
    - arn:aws:lambda:sa-east-1:425362996713:layer:Datadog-Extension-REY:58
  environment:
    DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT: localhost:4318
    DD_API_KEY: ${env:DD_API_KEY}
    DD_LOG_LEVEL: DEBUG
    DD_TRACE_ENABLED: true
    DD_SERVERLESS_LOGS_ENABLED: true
    NODE_OPTIONS: --require instrument

functions:
  code:
    handler: handler.handler
    url: true
