service: rey-node-otlp

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs18.x
  layers:
    - arn:aws:lambda:sa-east-1:464622532012:layer:Datadog-Extension:43
    - arn:aws:lambda:sa-east-1:184161586896:layer:opentelemetry-nodejs-0_1_0:1
  environment:
    AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler

    OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4318
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp

    DD_API_KEY: ${env:DD_API_KEY}
    DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT: localhost:4318
    DD_SERVERLESS_LOGS_ENABLED: true
    DD_TRACE_ENABLED: true

package:
  patterns:
    - '!**'
    - 'handler.js'

functions:
  code:
    handler: handler.handler
    url: true
